### ISSUE TITLE
*.edgekey.net problems

### ISSUE THREAD

**Issue by Gitoffomalawn** [Kees1958/WS3_annual_most_used_survey_blocklist#1]
Your lists includes an entry for `edgekey.net`, which causes many false positives on Pi-Hole and DNSCryptProxy. This is due to it being translated to `*.edgekey.net` in the blacklist, which in turns blocks many legitimate websites that use this service for domain aliasing. This is evident by a rise of entries in block logs with accompanying label `alias for LEGIT_WEBSITE_URL`, and a reference to `*.edgekey.net` as the blocking entry. 

Please remove this entry from the list to restore correct operation, as it seems to be overly broad.

**Comment by Kees1958** [comment]
Done, removed edgekey.net

**Comment by Gitoffomalawn** [comment]
Thanks for the speedy action.
