### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by rdsu-pt** [Kees1958/WS3_annual_most_used_survey_blocklist#3]
Hi,

Correct me if I'm wrong, but I found some issues in the list:
	
- 2mnd.net > 2mdn.net
- 2mdn.net: duplicated with previous
- eyeviewads.comt > eyeviewads.com
- ^^$third-party > ^$third-party
- ^third-party > ^$third-party
- $third-party > ^$third-party
- third-party > ^$third-party
- ^third-part > ^$third-party

Find and replace them by this order...

Thanks for your work!

**Comment by Kees1958** [comment]
Thanks will do that  Sunday morning Amsterdam time




On Sat, Feb 22, 2020 at 3:12 AM +0100, "rdsu-pt" <notifications@github.com> wrote:












Hi,


Correct me if I'm wrong, but I found some issues in the list:

2mnd.net > 2mdn.net
2mdn.net: duplicated with previous
eyeviewads.comt > eyeviewads.com
^^$third-party > ^$third-party
^third-party > ^$third-party
$third-party > ^$third-party
third-party > ^$third-party
^third-part > ^$third-party



Find and replace them by this order...


Thanks for your work!

**Comment by Kees1958** [comment]
Thanks a lot for your feedback, much appreciated. Hope I have corrected them all. Thanks again top
