### ISSUE TITLE
Top500 and GitHub avatar pictures

### ISSUE THREAD

**Issue by beerisgood** [Kees1958/WS3_annual_most_used_survey_blocklist#4]
The Top500 block
`||fastly.net^$third-party`

which then block (CNAME) avatar's on GitHub:
<img width="1071" alt="github" src="https://user-images.githubusercontent.com/9625159/76140925-4092b880-6057-11ea-82df-0d9fd3cb3d94.png">

Edit: Oh and other GitHub pictures too:
<img width="568" alt="screenshot" src="https://user-images.githubusercontent.com/9625159/76140940-7cc61900-6057-11ea-8382-78a81d763168.png">

Edit2: It break Reddit too:
<img width="1579" alt="reddit" src="https://user-images.githubusercontent.com/9625159/76141097-f4487800-6058-11ea-84f0-b67e93dc564e.png">

**Comment by Kees1958** [comment]
Removed, invited you as a contributor, so you can remove domains breaking websites also.
