### ISSUE TITLE
No UpDate since 4 Days in uBlockOrigin 1.50.1b*

### ISSUE THREAD

**Issue by Boersenfeger** [Kees1958/WS3_annual_most_used_survey_blocklist#78]
Hello, for about 4 days the list in uBlockOrigin 1.50.1b* is no longer updated. Is it possible to fix this? Thanks a lot
Bo

**Comment by Kees1958** [comment]
Do you use this version?

https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US_MV2_most_common_ad%2Btracking_networks

Due to editing limitation I hsd to create a file eith a new name

**Comment by Boersenfeger** [comment]
Thx, this works!
Great....
